### ISSUE TITLE
navバーが欲しい

### ISSUE THREAD

**Issue by tesso57** [tesso57/LinkPacketwithReact#55]
細かい仕様はまだ。とりあえず案だけ
- user検索ばー？
- packet検索ばー？

**Comment by tesso57** [comment]
イメージはGithubのnavバー

LinkPacket ホーム マイページの並び順

**Comment by tesso57** [comment]
検索バーは実装が重そうなので、検討中

**Comment by Sabaniki** [comment]
ええんちゃう？
