### ISSUE TITLE
パケットギャラリー

### ISSUE THREAD

**Issue by tesso57** [tesso57/LinkPacketwithReact#57]
- パケットギャラリーから「パケットギャラリー」を消す
- パケットの取得制限をかける
- パケットが最大2列にしかならないので、もっと増やす
- イメージはangular版の並び方 https://linkpacket.web.app/

**Comment by Sabaniki** [comment]
- パケットを日付順で出したい(これは簡単)
- パケットの取得制限も多分日付順で取るのと同じ雰囲気で取れるはず
-

**Comment by Sabaniki** [comment]
できたんちゃう？
